### ISSUE TITLE
Issue getting the extension running

### ISSUE THREAD

**Issue by arndom** [deepgram-devs/dg-translation-chrome-ext#10]
After following all the steps for getting started, the extension doesn't work, only getting errors:

![image](https://user-images.githubusercontent.com/40564798/195031916-7c32a747-a22c-4fc1-947d-809bdc56328d.png)
![image](https://user-images.githubusercontent.com/40564798/195031922-e5bc7819-9bc4-4614-b7bd-78c0cb2d9ba8.png)
<img width="173" alt="image" src="https://user-images.githubusercontent.com/40564798/195032859-0094bf4f-977c-4e31-ad1d-11729b19edab.png">

Steps to replicate:

-  Clone repo
- yarn & yarn dev
- load as unpacked extension: `dg-translation-chrome-ext/src`

**Comment by BekahHW** [comment]
Can you tell me about your environment?

Operating System/Version: 
Language: 
Browser:

**Comment by arndom** [comment]
Ok

OS: Windows 11
Language: English
Browser: Chrome

**Comment by BekahHW** [comment]
Ok, @arndom, can you try to get the latest version of the repo and then run yarn again? I think it was somehow missing the TypeScript devDependency. This should solve it.

**Comment by BekahHW** [comment]
Just to clarify, you stopped the server, ran yarn, and then ran yarn start?

And your package json file include typescript as a devdependency now right?

**Comment by arndom** [comment]
Yes, I have done all that and checked that typescript is present:
<img width="559" alt="image" src="https://user-images.githubusercontent.com/40564798/195163859-8f79c559-40f9-4640-b4d8-ffadb8ca77e9.png">

**Comment by BekahHW** [comment]
Ok, let's try this:

Delete `.parcel-cache`, `dist`, `node_modules`, `yarn.lock`.

Run `yarn` and then `yarn start`.

Hopefully, this fixes the problem. 

Just double checking, you don't have a `package-lock.json` file, right? If you do, delete that as well.

**Comment by arndom** [comment]
@BekahHW, so...I've tried it but still get the same error.

Also, I've tried loading the unpacked extension from `dist` instead of `src` and have been getting:
<img width="512" alt="image" src="https://user-images.githubusercontent.com/40564798/195441878-a62ece84-204e-4805-b580-f4a7d87a511b.png">

**Comment by BekahHW** [comment]
I can't do it today,  but do you want to do a video call in the next couple of days and see if we can get it working together?

**Comment by arndom** [comment]
Sure, that would be really helpful...when would you be available?

**Comment by BekahHW** [comment]
@arndom I think I figured it out. I missed a step in the readme. I have it all updated now, but here are a couple of updates. Notice that we're loading from the `dist folder` now.

- Run `yarn` to install the dependencies.
- Run `yarn build`. 
- To load this extension unpacked, navigate to `/dg-translation-chrome-ext/dist`.

**Comment by arndom** [comment]
@BekahHW I tried it; here's my result:

![image](https://user-images.githubusercontent.com/40564798/195616654-04546d89-3a39-4c80-9468-a843f6e8f0d9.png)

**Comment by arndom** [comment]
@BekahHW I got it past the previous error by editing the generated popjs in the `dist` folder to use the generated `content-script`.....it asks to choose a tab to share audio but I cant seem to find the transcription of the playing video.

**Comment by muckitymuck** [comment]
This is the error I am getting trying to get this to work:
![image](https://user-images.githubusercontent.com/6893378/196058917-3724b66b-e81e-4838-ada4-6140646e72dc.png)

**Comment by arndom** [comment]
@BekahHW I got the error not to come up consistently by changing the way the `popup.ts` reads the `content-script`, issue now is that it seems to be sharing my audio, but I can't see any transcription.
> 
> ![image](https://user-images.githubusercontent.com/40564798/195616654-04546d89-3a39-4c80-9468-a843f6e8f0d9.png)


- my fix:

`popup.ts`:
<img width="454" alt="image" src="https://user-images.githubusercontent.com/40564798/197182540-c43e63fd-dad7-4618-b039-50e8c2eda37a.png">

`content-script.ts`:
<img width="510" alt="image" src="https://user-images.githubusercontent.com/40564798/197182705-7dc4f816-4e89-4f0d-817f-8e4c7cd3f320.png">

`popup.html`:
<img width="277" alt="image" src="https://user-images.githubusercontent.com/40564798/197182778-eaaf4a01-70d3-4022-8145-4ea78310cf8b.png">

**Comment by BekahHW** [comment]
That's great news, @arndom. Do you want to create a PR for this and I'll merge in the fix?

**Comment by arndom** [comment]
@BekahHW, Here's the PR: https://github.com/deepgram-devs/dg-translation-chrome-ext/pull/18

**Comment by BekahHW** [comment]
@arndom did you delete .parcel-cache, dist, node_modules, yarn.lock, and then run `yarn`, `yarn build`, and then `yarn start`? I'm getting a different error
 
<img width="600" alt="image" src="https://user-images.githubusercontent.com/34313413/197246866-228b2df5-3cbc-439a-bfc1-ca46c7e39122.png">

**Comment by arndom** [comment]
Yes I did all that, that error seems to happen when the manage extension tab is open: `chrome://extensions/`, I closed the tab and reloaded the extension to get it working

**Comment by BekahHW** [comment]
@arndom it's interesting bc I can console.log the transcript in `showLatestTranscript()` and it shows up in my console, but I'm not getting it in the `popup.html.` Feels like we're getting closer though

**Comment by BekahHW** [comment]
@arndom I just pushed up a fix. Should be working now!

**Comment by arndom** [comment]
awesome, I'll pull and try

**Comment by arndom** [comment]
@BekahHW It's working 

![CrazyDanceFunnyDanceGIF](https://user-images.githubusercontent.com/40564798/197252947-41246281-7085-4056-b7aa-15d68f86d518.gif)

**Comment by BekahHW** [comment]
@arndom ![high five gif](https://media.giphy.com/media/WYyvz9PIhjLHgiyvR2/giphy.gif)
